"""Run with ``python -m streamlit run app.py`` after prepare and train."""

import json
from contextlib import closing
import os
from pathlib import Path
import sqlite3

import joblib
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from stocksense.inventory import replenishment_plan
from stocksense.ui import apply_style, page_header, sidebar_brand, style_figure


ROOT = Path(os.environ.get("STOCKSENSE_HOME", Path(__file__).resolve().parent))
METHOD_NAMES = {
    "previous_week": "Previous week",
    "trailing_4_week": "Trailing four-week average",
    "tree": "Random forest",
}
MODEL_NAMES = {
    **METHOD_NAMES,
    "forest_small": "Random forest · small",
    "forest_flexible": "Random forest · flexible",
}


@st.cache_data(show_spinner=False)
def read_database(path: str, modified: float) -> dict[str, pd.DataFrame]:
    """The timestamp invalidates the cache after rebuilding the database."""
    del modified
    with closing(sqlite3.connect(f"file:{Path(path).as_posix()}?mode=ro", uri=True)) as connection:
        tables = {
            name: pd.read_sql_query(f"SELECT * FROM {name}", connection)
            for name in ["weekly_sales", "products", "daily_sales", "quality_counts"]
        }
    tables["weekly_sales"]["week"] = pd.to_datetime(tables["weekly_sales"]["week"])
    tables["daily_sales"]["date"] = pd.to_datetime(tables["daily_sales"]["date"])
    for name in ["weekly_sales", "products"]:
        tables[name]["stock_code"] = tables[name]["stock_code"].astype(str)
    return tables


@st.cache_resource(show_spinner=False)
def read_model(path: str, modified: float):
    del modified
    # Only load the local artifact generated by this project's train command.
    return joblib.load(path)


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def display_metrics(frame: pd.DataFrame) -> pd.DataFrame:
    """Present the saved evaluation in readable, consistently formatted columns."""
    result = frame.copy()
    result = result.drop(columns=["scope"], errors="ignore")
    for column in ("stock_code", "horizon"):
        if column in result and (result[column].isna().all() or
                                 (column == "stock_code" and result[column].nunique() <= 1)):
            result = result.drop(columns=column)
    if "model" in result:
        result["model"] = result["model"].map(lambda value: MODEL_NAMES.get(value, value))
    if "wape" in result:
        result["WAPE"] = result.pop("wape").map(
            lambda value: "N/A · zero actual sales" if pd.isna(value) else f"{value:.2%}"
        )
    if "mae" in result:
        result["MAE (units)"] = result.pop("mae").round(2)
    return result.rename(columns={"model": "Method", "stock_code": "Product", "horizon": "Weeks ahead",
                                  "n_predictions": "Forecasts", "actual_total": "Observed units"})


def show_exploration(tables: dict, quality: dict) -> None:
    st.subheader("Understand the sales history")
    st.caption("Explore recorded volume, seasonal patterns, and the quality of the source data.")
    daily = tables["daily_sales"].sort_values("date")
    if not daily.empty:
        monthly = daily.set_index("date")["sales"].resample("MS").sum().reset_index()
        st.plotly_chart(style_figure(px.line(monthly, x="date", y="sales", markers=True,
                               color_discrete_sequence=["#137c66"],
                               labels={"date": "Month", "sales": "Recorded units"},
                               title="Monthly sales · all products and countries")),
                        use_container_width=True, theme=None, config={"displayModeBar": False})
        st.caption("Boundary months can be partial. These totals describe recorded positive sales; "
                   "they exclude returns and cancellations.")
    left, right = st.columns(2)
    with left:
        top = tables["products"].nlargest(10, "training_units").copy()
        top["label"] = top["stock_code"] + " · " + top["description"].fillna("").str.slice(0, 35)
        st.plotly_chart(style_figure(px.bar(top.sort_values("training_units"), x="training_units", y="label",
                              color_discrete_sequence=["#617a8a"],
                              orientation="h", labels={"training_units": "Training-period units", "label": ""},
                              title="Top products · training period"), height=420),
                        use_container_width=True, theme=None, config={"displayModeBar": False})
    with right:
        weekly = tables["weekly_sales"].groupby("week", as_index=False)["sales"].sum()
        weekly["month"] = weekly["week"].dt.month
        seasonal = weekly.groupby("month", as_index=False)["sales"].mean()
        st.plotly_chart(style_figure(px.bar(seasonal, x="month", y="sales",
                              color_discrete_sequence=["#137c66"],
                              labels={"month": "Calendar month of week start", "sales": "Mean weekly units"},
                              title="Seasonal profile · selected products"), height=420),
                        use_container_width=True, theme=None, config={"displayModeBar": False})
        st.caption("Uses all available complete weeks for exploration. About two annual cycles "
                   "cannot establish stable seasonality; this chart is not used to choose the model.")

    st.subheader("Observations from this run")
    if not tables["products"].empty:
        leader = tables["products"].sort_values("training_units", ascending=False).iloc[0]
        st.write(f"• Product {leader['stock_code']} had the largest training-period volume among "
                 f"selected products: {leader['training_units']:,.0f} units.")
    zero_share = tables["weekly_sales"]["sales"].eq(0).mean()
    st.write(f"• {zero_share:.1%} of product-week observations have zero recorded sales. "
             "A zero can mean no purchases, a listing gap, or a stockout; this dataset cannot distinguish them.")
    if not seasonal.empty:
        peak = seasonal.loc[seasonal["sales"].idxmax()]
        st.write(f"• Month {int(peak['month'])} has the highest average weekly volume for the selected "
                 "products in this sample. This is a descriptive observation, not evidence of future growth.")

    st.subheader("Data-quality audit")
    st.write("Product codes are stored as text. The pipeline explicitly audits duplicates, missing "
             "values, cancellation invoices, returns, invalid prices, and non-product codes.")
    excluded = quality.get("excluded", {})
    flags = quality.get("flags", {})
    left, right = st.columns(2)
    with left:
        st.markdown("**Sequential exclusions**")
        if excluded:
            st.dataframe(pd.DataFrame(excluded.items(), columns=["Reason", "Rows"]), hide_index=True)
        else:
            st.dataframe(tables["quality_counts"], hide_index=True)
        st.caption("Each excluded row is assigned its first exclusion reason, so these counts are disjoint.")
    with right:
        st.markdown("**Raw-data flags**")
        if flags:
            st.dataframe(pd.DataFrame(flags.items(), columns=["Flag", "Rows"]), hide_index=True)
        st.caption("Flags can overlap: one raw row may have multiple issues.")
    st.write("Weekly series use Monday-start weeks. Missing product weeks inside the complete observed "
             "calendar are filled with zero recorded units. Boundary partial weeks are dropped so a "
             "short week is not compared with a full week.")
    with st.expander("Processing details and audit metadata"):
        st.json(quality)


def show_evaluation(root: Path, product: str, summary: dict) -> None:
    st.subheader("Compare forecasting methods")
    st.caption("Lower error is better. The default is selected on validation; the final test measures how it generalizes.")
    metrics_path = root / "artifacts/test_metrics.csv"
    if not metrics_path.exists():
        st.info("Run `python -m stocksense train` to generate evaluation results.")
        return
    metrics = pd.read_csv(metrics_path, dtype={"stock_code": str})
    chosen = METHOD_NAMES.get(summary.get("selected_method"), "Not available")
    st.info(f"Selected on validation: {chosen}. The selection stays fixed after viewing the final test.")
    left, right = st.columns(2, gap="large")
    columns = ["Method", "MAE (units)", "WAPE"]
    with left, st.container(border=True, key="panel-validation"):
        st.caption("01 / MODEL SELECTION")
        st.markdown("### Rolling validation")
        validation_path = root / "artifacts/validation_metrics.csv"
        if validation_path.exists():
            validation = pd.read_csv(validation_path, dtype={"stock_code": str})
            st.dataframe(display_metrics(validation[validation["scope"].eq("overall")])[columns],
                         hide_index=True, use_container_width=True)
        st.caption(f"Week starts {summary.get('validation_start', '—')} to {summary.get('validation_end', '—')}.")
    with right, st.container(border=True, key="panel-test"):
        st.caption("02 / FINAL EVALUATION")
        st.markdown("### Held-out test")
        st.dataframe(display_metrics(metrics[metrics["scope"].eq("overall")])[columns],
                     hide_index=True, use_container_width=True)
        st.caption(f"Week starts {summary.get('test_start', '—')} to {summary.get('test_end', '—')}.")

    with st.container(border=True, key="panel-product"):
        st.markdown(f"### Product {product}")
        st.caption("Final-test performance for your selected product.")
        selected = metrics[metrics["stock_code"].eq(product) & metrics["scope"].eq("product")]
        st.dataframe(display_metrics(selected), hide_index=True, use_container_width=True)
        with st.expander("Compare errors by forecast horizon"):
            st.markdown("**All selected products**")
            st.dataframe(display_metrics(metrics[metrics["scope"].eq("horizon")]),
                         hide_index=True, use_container_width=True)
            st.markdown(f"**Product {product}**")
            st.dataframe(display_metrics(metrics[metrics["stock_code"].eq(product) & metrics["scope"].eq("product_horizon")]),
                         hide_index=True, use_container_width=True)

    st.subheader("Where simpler methods do better")
    st.caption("Product-level cases where the tree has higher test error than a baseline.")
    failure_path = root / "artifacts/failure_cases.csv"
    if failure_path.exists():
        failures = pd.read_csv(failure_path, dtype={"stock_code": str})
        if failures.empty:
            st.write("No worse-than-baseline cases were recorded by this run's failure-case definition.")
        else:
            failures["baseline"] = failures["baseline"].map(METHOD_NAMES)
            readable = failures[["stock_code", "baseline", "mae_tree", "mae_baseline", "mae_gap"]].head(20).round(2)
            st.dataframe(readable.rename(columns={"stock_code": "Product", "baseline": "Better baseline",
                                                 "mae_tree": "Tree MAE", "mae_baseline": "Baseline MAE",
                                                 "mae_gap": "Extra error (units)"}),
                         hide_index=True, use_container_width=True)
            st.caption("Showing up to 20 comparisons, ordered by extra error. A more complex model is not automatically better.")
    with st.expander("Understanding the metrics and evaluation"):
        st.write("MAE is the average absolute error in units per product-week forecast. WAPE divides "
                 "the total absolute error by total observed units, so high-volume products have more "
                 "influence. Both should be lower. WAPE is N/A when total actual sales are zero.")
        st.write("Chronological rolling validation chooses the method. Final-test scores do not change "
                 "that choice. Each four-week block uses only earlier observations; predictions are fed "
                 "back recursively within the block. After a block has elapsed, its actuals can be used "
                 "to refit at the next origin.")
    with st.expander("Split dates and experiment details"):
        st.json(summary)


def main() -> None:
    st.set_page_config(page_title="StockSense · Sales & Inventory", page_icon="📦", layout="wide")
    apply_style()
    page_header()
    sidebar_brand()
    database = ROOT / "data/processed/stocksense.sqlite"
    if not database.exists():
        st.warning("Prepare the UCI data to start StockSense.")
        st.code("python -m stocksense download\npython -m stocksense inspect\n"
                "python -m stocksense prepare\npython -m stocksense train\n"
                "python -m streamlit run app.py", language="bash")
        st.write("See README.md for the dataset download link and exact manual download instructions.")
        st.stop()

    tables = read_database(str(database), database.stat().st_mtime)
    history = tables["weekly_sales"].sort_values(["stock_code", "week"])
    quality = read_json(ROOT / "reports/data_quality.json")
    summary = read_json(ROOT / "artifacts/evaluation_summary.json")
    if (quality.get("weekly_sha256") and summary.get("weekly_sha256")
            and quality["weekly_sha256"] != summary["weekly_sha256"]):
        st.error("Prepared data has changed since these model artifacts were generated. "
                 "Retrain before displaying forecasts or comparing scores.")
        st.code("python -m stocksense train", language="bash")
        st.stop()
    if history.empty or tables["products"].empty:
        st.error("The prepared database has no selected product history. Rerun the prepare command.")
        st.stop()

    cutoff = history["week"].max() + pd.Timedelta(days=6)
    columns = st.columns(4)
    columns[0].metric("Products in scope", history["stock_code"].nunique())
    columns[1].metric("Weeks of history", history["week"].nunique())
    columns[2].metric("Clean sales records", f"{quality.get('clean_rows', 0):,}")
    columns[3].metric("History through", cutoff.strftime("%d %b %Y"))
    st.caption("30 high-volume products selected using training data only. Sales-record count covers all cleaned products and countries."
               if history["stock_code"].nunique() == 30 else
               "Products selected using training data only. Sales-record count covers all cleaned products and countries.")

    products = tables["products"].sort_values("training_units", ascending=False)
    labels = dict(zip(products["stock_code"], products["description"].fillna("Unknown product")))
    st.sidebar.markdown("### Your forecast")
    st.sidebar.caption("Choose a product and planning horizon.")
    product = st.sidebar.selectbox("Product", products["stock_code"].tolist(),
                                   format_func=lambda code: f"{code} · {labels[code]}")
    horizon = st.sidebar.slider("Weeks to show", 1, 4, 4)
    model_path = ROOT / "artifacts/deployment_model.joblib"
    methods = list(METHOD_NAMES) if model_path.exists() else ["previous_week", "trailing_4_week"]
    selected_method = summary.get("selected_method", "previous_week")
    if selected_method not in methods:
        selected_method = "previous_week"
    method = st.sidebar.selectbox("Forecast method", methods, index=methods.index(selected_method),
                                  format_func=METHOD_NAMES.get)
    if summary:
        st.sidebar.caption(f"Validation-selected default: {METHOD_NAMES.get(selected_method, selected_method)}. "
                           "You can switch methods to compare their behavior.")
    else:
        st.sidebar.caption("Run the train command for model comparison and a validation-selected default.")
    st.sidebar.divider()
    st.sidebar.markdown("**About this workspace**")
    st.sidebar.caption("UCI Online Retail II · 2009–2011")
    st.sidebar.caption("Historical forecasts and hypothetical inventory. No live stock connection.")

    forecast_tab, evaluation_tab, exploration_tab = st.tabs(
        ["Forecast & inventory", "Model performance", "Data & insights"]
    )
    with forecast_tab:
        from stocksense.forecasting import forecast

        model = read_model(str(model_path), model_path.stat().st_mtime) if method == "tree" else None
        with st.spinner("Calculating future weekly sales…"):
            predictions = forecast(history, horizon=4, method=method, model=model)
        future = predictions[predictions["stock_code"].astype(str).eq(product)].sort_values("week")
        shown_future = future.head(horizon)
        observed = history[history["stock_code"].eq(product)].tail(52)
        chart_column, planner_column = st.columns([2.05, 1], gap="large")
        with chart_column, st.container(border=True, key="panel-forecast"):
            st.caption(f"PRODUCT {product}  /  WEEKLY SALES")
            st.subheader(labels[product].capitalize())
            st.caption(f"{METHOD_NAMES[method]} · {horizon}-week outlook · units sold")
            figure = go.Figure()
            figure.add_scatter(x=observed["week"], y=observed["sales"], mode="lines", name="Recorded sales",
                               line={"color": "#617a8a", "width": 2}, fill="tozeroy",
                               fillcolor="rgba(97,122,138,0.06)")
            figure.add_scatter(x=shown_future["week"], y=shown_future["prediction"], mode="lines+markers",
                               name="Forecast", line={"color": "#137c66", "dash": "dash", "width": 3},
                               marker={"size": 7, "color": "#137c66"})
            figure.add_vrect(x0=future["week"].min() - pd.Timedelta(days=3),
                             x1=shown_future["week"].max() + pd.Timedelta(days=3),
                             fillcolor="rgba(19,124,102,0.06)", line_width=0, layer="below")
            figure.update_layout(xaxis_title=None, yaxis_title="Units", hovermode="x unified")
            st.plotly_chart(style_figure(figure, height=310), use_container_width=True,
                            theme=None, config={"displayModeBar": False})
            st.caption("Last 52 complete weeks. Shaded green area shows the forecast period.")
            st.markdown("**Weekly outlook**")
            outlook = shown_future[["week", "horizon", "prediction"]].copy()
            outlook["week"] = outlook["week"].dt.strftime("%d %b %Y")
            outlook["prediction"] = outlook["prediction"].round(1)
            st.dataframe(outlook.rename(columns={"week": "Week starting", "horizon": "Weeks ahead",
                                                 "prediction": "Forecast units"}),
                         hide_index=True, use_container_width=True)
            st.caption("Point estimates, without prediction intervals. Each future week uses earlier predictions, not future actual sales.")

        with planner_column, st.container(border=True, key="panel-inventory"):
            st.caption("PLANNING SIMULATION")
            st.subheader("Plan replenishment")
            st.caption("Adjust your inventory assumptions. All quantities are in units.")
            current = st.number_input("Current stock", min_value=0.0, value=0.0, step=1.0)
            incoming = st.number_input("Stock already on order", min_value=0.0, value=0.0, step=1.0)
            lead = st.number_input("Supplier lead time (weeks)", min_value=1, max_value=4, value=2, step=1)
            safety = st.number_input("Safety stock", min_value=0.0, value=0.0, step=1.0)
            plan = replenishment_plan(future["prediction"].tolist(), current, incoming, int(lead), safety)
            st.divider()
            st.metric("Suggested replenishment", f"{plan.replenishment_quantity:,} units")
            st.caption(f"Forecast during lead time: {plan.forecast_during_lead_time:,.1f} units  ·  "
                       f"Stock + incoming: {current + incoming:,.1f} units")
            if lead > horizon:
                st.caption(f"The planner uses {lead} forecast weeks; the chart currently displays {horizon}.")
            with st.expander("Calculation & arrival assumptions"):
                st.write("Lead-time forecast + safety stock − current stock − incoming stock. "
                         "The suggested order is rounded up to whole units, with a minimum of zero.")
                st.write("All incoming stock must arrive before it is needed during the lead time. "
                         "A new order arrives at the end of that period and cannot prevent an imminent stockout. "
                         "Arrival schedules, order minimums, pack sizes, costs, and service levels are not modeled.")
            st.caption("Only include incoming stock that will arrive before it is needed.")

    with evaluation_tab:
        show_evaluation(ROOT, product, summary)
    with exploration_tab:
        show_exploration(tables, quality)

    st.divider()
    st.caption("Observed sales are a proxy for demand. The source has no stock levels or lost-sales records, "
             "so demand lost through stockouts cannot be recovered. Historical accuracy does not establish "
             "cost savings or fewer stockouts. This prototype provides a planning simulation only.")
    st.caption("Data: [UCI Online Retail II](https://archive.ics.uci.edu/dataset/502/online+retail+ii), "
                "Daqing Chen, [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). "
                "[Dataset DOI](https://doi.org/10.24432/C5CG6D).")


if __name__ == "__main__":
    main()
